### PR TITLE
Mostly-Fluid-Rishabh Khanna

### PR DESCRIPTION
**Pull request by Rishabhk07**

### CODE REVIEW

**Comment by aayusharora** [comment]
@Rishabhk07 Hey !! Thanks, Please do it like this. 
Make a folder by your name and put these files inside them. This will help me to merge without conflicts. :)

**Comment by Rishabhk07** [comment]
Hey !! Thank you. i have made a folder with my name in my local repo and have put all these files init but how do i make the code of column Drop same as when i forked(original file) so that no merge conflicts occur ?

**Comment by aayusharora** [comment]
@Rishabhk07 1. Lets say you make a folder by your name.
                        2. Put these files inside them
                        3. Push it and generate PR.
No need to make the code same. There will be no conflicts as your folder will not effect my existing files :)

**Comment by Rishabhk07** [comment]
@aayusharora hey, i have generated a new PR with files in a folder with my name, please review it for any merge conflicts. Thank you :)

**Comment by aayusharora** [comment]
@Rishabhk07  Thanks !! You have done it correctly , but the PR also shown some unnecessary files like Column-Drop/column-drop.html .Just keep your folder and remove all extra files https://github.com/aayusharora/ResponsiveDesign/pull/4/files

**Comment by Rishabhk07** [comment]
@aayusharora  i have removed all the extra files only folder with my name is present in my PR. Thank you. can i ask a question ? merge conflicts were happening bcoz i had made some changes in the original file ? to remove those changes i removed the files to which i made the changes ? this is what happened here right ? Thank you :)

**Comment by aayusharora** [comment]
In all the rest 3 remaining  PR's the same file is changing it's code at same lines. Merginganyone in the main code will provide merge conflicts to all other files. What we want here is 

1.  The original code or practice files to be unaffected
2.  Folders by persons name with their completed tasks.

Thanks for doing this :)

**Comment by Rishabhk07** [comment]
@aayusharora hey !!  Thank you so much for the guidance and the merge :) , will generate another PR after implementing   Layout-Shifter. Thank you :)

**Pull request merged**
