### PR TITLE
mansi khemka elixir

### PR DESCRIPTION
**Pull request by mansikhemka**

### CODE REVIEW

**Comment by aayusharora** [comment]
Hey @mansikhemka  Thanks !! Please make a folder by your name , put these files inside them and generate PR. I will be able to merge it then. :)

**Comment by mansikhemka** [comment]
I am sorry I am a little late! But I have made the folder.

**Comment by mansikhemka** [comment]
Hello Sir, 
Mansi this side. I was late in seeing the email you sent me so made the folder right now for ResponsiveDesigns on github by my name.
I will be glad if you could merge it as it will help me in hacktoberfest!

Mansi Khemka
Elixir Fall 2016

**Comment by aayusharora** [comment]
Yeah Thanks @mansikhemka :)

**Pull request merged**
